Parameters:
  BucketNameParameter:
    Type: String
    Description: Bucket Name
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: 
        !Join
          - '-'
          - - !Ref AWS::AccountId
            - !Ref BucketNameParameter
Outputs:
  BucketName:
    Description: The Name of the S3 bucket
    Value: !GetAtt S3Bucket.RegionalDomainName
