Parameters:
  BucketNameParameter:
    Type: String
    Description: Bucket Name
Resources:
  S3EncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: 
        !Join
          - '-'
          - - !Ref AWS::AccountId
            - !Ref BucketNameParameter
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID:
                Ref: S3EncryptionKey
              SSEAlgorithm: aws:kms
Outputs:
  BucketName:
    Description: The Name of the S3 bucket
    Value: !GetAtt S3Bucket.RegionalDomainName
